//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Open_Schooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center_Login_Information
    {
        public int Id { get; set; }
        public Nullable<double> UDISE_No { get; set; }
        public string Center_Password { get; set; }
        public string Division { get; set; }
        public string Div_Code { get; set; }
        public string District { get; set; }
        public string Taluka { get; set; }
        public string Contact_Center_Code { get; set; }
        public string Center_Name { get; set; }
        public Nullable<double> Contact { get; set; }
        public string Medium { get; set; }
        public string Active { get; set; }
        public Nullable<int> District_Code { get; set; }
    }
}
