//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Open_Schooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_District
    {
        public int Id { get; set; }
        public string District { get; set; }
        public string DivCode { get; set; }
    }
}
