//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Open_Schooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Subject
    {
        public int Id { get; set; }
        public string Subject_Code { get; set; }
        public string Subject_Name { get; set; }
        public string Subject_Group { get; set; }
        public string Handicaped { get; set; }
        public string Class { get; set; }
        public string sample2 { get; set; }
    }
}
