//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Open_Schooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CenterList
    {
        public int Id { get; set; }
        public string division { get; set; }
        public string div_code { get; set; }
        public string district { get; set; }
        public string taluka { get; set; }
        public string center_code { get; set; }
        public string center_name { get; set; }
        public string Medium { get; set; }
        public string active { get; set; }
    }
}
