//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Open_Schooling.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Tbl_Application_Form
    {
        public string Form_No { get; set; }
        public string UDISE_No { get; set; }
        public string Contact_center { get; set; }
        public string Last_name { get; set; }
        public string Name { get; set; }
        public string Middle_name { get; set; }
        public string Mother_name { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string Mobile_no { get; set; }
        public string Place_of_birth { get; set; }
        public string Date_of_birth { get; set; }
        public string Adhar_no { get; set; }
        public string Gender { get; set; }
        public string Minority_Religion { get; set; }
        public string Category { get; set; }
        public string Divyang { get; set; }
        public string Medium { get; set; }
        public string Type_Of_User { get; set; }
        public string Subjects { get; set; }
        public string Subject1 { get; set; }
        public string Subject2 { get; set; }
        public string Subject3 { get; set; }
        public string Subject4 { get; set; }
        public string Subject5 { get; set; }
        public string EC_Year { get; set; }
        public string EC_Number { get; set; }
        public string LastExamYear { get; set; }
        public string LastExamSeatNo { get; set; }
        public string Year_Id { get; set; }
        public string Ip { get; set; }
        public string DateNow { get; set; }
        public string Photo { get; set; }
        public string Signature { get; set; }
        public int Id { get; set; }
        public string Seat_No { get; set; }
        public HttpPostedFileBase Upload_Photo { get; set; }
        public HttpPostedFileBase Upload_Sign { get; set; }
    }
}
